name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # 코드가 push될 때 작동합니다

# GITHUB_TOKEN에 쓰기 권한을 부여하여 Pages에 배포할 수 있도록 합니다
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Set up Node
        uses: actions/node-setup@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/public' # 빌드된 결과물이 저장되는 폴더입니다

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
